import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import LoginButtons from "./components/LoginButtons";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} pt-4 pl-4 pr-4`}>
        <header className="w-full flex items-center mt-2 mb-2 flex-wrap">
          <Nav />
          <LoginButtons />
        </header>
        <main className="p-5">{children}</main>
      </body>
    </html>
  );
}
